import type { Theme } from './types';

export const THEMES: readonly Theme[] = [
  {
    id: 'fed',
    displayName: 'FED · Politică Monetară',
    shortLabel: 'FED',
    description: 'Federal Reserve, dobânzi americane, Powell, FOMC',
    keywords: [
      'fed', 'powell', 'fomc', 'jerome powell', 'rezerva federală',
      'rezerva federala', 'federal reserve', 'fed minutes', 'fed funds',
      'rata dobânzii', 'rata dobanzii', 'dobanda fed', 'minutele fed',
      'majorare dobandă', 'majorare dobanda', 'cut dobandă', 'cut dobanda',
      'tapering', 'qe', 'quantitative easing',
    ],
  },
  {
    id: 'crypto',
    displayName: 'Crypto · Digital Assets',
    shortLabel: 'CRYPTO',
    description: 'Bitcoin, Ethereum, alte criptomonede, DeFi',
    keywords: [
      'bitcoin', 'btc', 'ethereum', 'eth', 'crypto', 'criptomonedă',
      'criptomoneda', 'cripto', 'altcoin', 'defi', 'nft', 'blockchain',
      'binance', 'coinbase', 'solana', 'sol', 'xrp', 'doge', 'stablecoin',
      'usdt', 'usdc', 'web3', 'mining', 'staking', 'halving',
    ],
  },
  {
    id: 'stocks_us',
    displayName: 'Acțiuni SUA · Wall Street',
    shortLabel: 'STOCKS US',
    description: 'S&P 500, NASDAQ, tech stocks, big caps americane',
    keywords: [
      's&p 500', 'sp500', 'spx', 'nasdaq', 'dow jones', 'dow', 'wall street',
      'nvidia', 'nvda', 'apple', 'aapl', 'microsoft', 'msft', 'tesla', 'tsla',
      'meta', 'amazon', 'amzn', 'google', 'googl', 'magnificent seven',
      'mag 7', 'mag7', 'tech stocks', 'big tech', 'earnings season',
      'raport nvidia', 'raport apple', 'q3 earnings', 'q4 earnings',
      'bursa americană', 'bursa americana',
    ],
  },
  {
    id: 'gold',
    displayName: 'Aur · Metale Prețioase',
    shortLabel: 'AUR',
    description: 'Aur, argint, metale prețioase ca refugiu',
    keywords: [
      'aur', 'xau', 'gold', 'argint', 'silver', 'metale prețioase',
      'metale pretioase', 'refugiu tradițional', 'refugiu traditional',
      'safe haven', 'comex', 'lingouri', 'gold standard',
    ],
  },
  {
    id: 'forex',
    displayName: 'Forex · Valute',
    shortLabel: 'FOREX',
    description: 'Dolar, euro, valute, DXY, carry trade',
    keywords: [
      'dxy', 'dolar', 'dollar', 'usd', 'eur/usd', 'eurusd', 'forex',
      'valută', 'valuta', 'carry trade', 'yen', 'jpy', 'gbp', 'cnh',
      'cny', 'aud', 'cad', 'paritate', 'curs valutar',
      'aspiratorul global', 'lichiditate globală', 'lichiditate globala',
    ],
  },
  {
    id: 'real_estate',
    displayName: 'Imobiliare · Locuințe',
    shortLabel: 'IMOBILIARE',
    description: 'Piață imobiliară, locuințe, ipoteci, construcții',
    keywords: [
      'imobiliar', 'imobiliare', 'real estate', 'locuințe', 'locuinte',
      'apartament', 'ipotec', 'mortgage', 'casă', 'casa', 'construc',
      'home depot', 'housing', 'piața imobiliară', 'piata imobiliara',
      'renovă', 'renova', 'renovări', 'renovari',
    ],
  },
  {
    id: 'economy_eu',
    displayName: 'Economie UE · BCE',
    shortLabel: 'EU',
    description: 'BCE, euro, Uniunea Europeană, Lagarde, Germania, Franța',
    keywords: [
      'bce', 'ecb', 'banca centrală europeană', 'banca centrala europeana',
      'lagarde', 'christine lagarde', 'uniunea europeană', 'uniunea europeana',
      'germania', 'bundesbank', 'franța', 'franta', 'italia', 'spania',
      'eurozonă', 'eurozona', 'euro area', 'pib germania',
    ],
  },
  {
    id: 'macro',
    displayName: 'Macro · Economia Globală',
    shortLabel: 'MACRO',
    description: 'Inflație, recesiune, PIB, șomaj, indicatori macro generali',
    keywords: [
      'inflație', 'inflatia', 'inflation', 'cpi', 'ppi', 'pce',
      'recesiune', 'recession', 'pib', 'gdp', 'șomaj', 'somaj',
      'unemployment', 'nfp', 'non-farm payrolls', 'jobs report',
      'consumer confidence', 'pmi', 'manufacturing pmi',
      'trade-down', 'walmart', 'target', 'tjx', 'consumer spending',
      'retail sales', 'yield curve', 'curba randamentelor',
    ],
  },
  {
    id: 'education',
    displayName: 'Educație Financiară',
    shortLabel: 'EDUCATION',
    description: 'Concepte de bază, definiții, cum funcționează lucrurile în finanțe',
    keywords: [
      'compound interest', 'dobândă compusă', 'dobanda compusa',
      'inflație ce înseamnă', 'inflatie ce inseamna',
      'pib ce înseamnă', 'pib ce inseamna', 'gdp explained',
      'cum funcționează', 'cum functioneaza',
      'pe înțelesul tuturor', 'pe intelesul tuturor',
      'a opta minune', 'opta minune',
      'einstein', 'feynman', 'buffett a spus', 'warren buffett',
      'definiție', 'definitie', 'concept de bază', 'concept de baza',
      'educație financiară', 'educatie financiara',
      'lecții financiare', 'lectii financiare',
      'principii de bază', 'principii de baza',
    ],
  },
  {
    id: 'investing_principles',
    displayName: 'Principii Investiționale',
    shortLabel: 'INVESTING',
    description: 'Diversificare, risk management, alocare, dollar cost averaging',
    keywords: [
      'diversificare', 'diversifica',
      'toate ouăle', 'toate ouale', 'eggs in one basket',
      'risc', 'risk management', 'managementul riscului',
      'alocare', 'asset allocation', 'portofoliu',
      'portfolio', 'dca', 'dollar cost averaging',
      'rebalansare', 'rebalancing',
      'hedge', 'hedging', 'protecție', 'protectie',
      'long term', 'pe termen lung',
      'value investing', 'growth investing',
      'index fund', 'index funds', 'etf', 'etfs',
      'lump sum',
    ],
  },
  {
    id: 'trading_strategy',
    displayName: 'Strategie Trading',
    shortLabel: 'TRADING',
    description: 'Psihologia pieței, timing, trading patterns, technical analysis',
    keywords: [
      'trading', 'trader', 'day trading',
      'swing trade', 'scalping',
      'psihologia pieței', 'psihologia pietei',
      'fomo', 'fud', 'fear and greed',
      'support', 'resistance', 'rezistență', 'rezistenta',
      'breakout', 'breakdown',
      'momentum', 'trend',
      'algoritm', 'algoritmi',
      'curățare piață', 'curatare piata',
      'weekly brief', 'piața săptămânii', 'piata saptamanii',
      'luni și marți', 'luni si marti',
      'technical analysis', 'analiză tehnică', 'analiza tehnica',
    ],
  },
  {
    id: 'emerging_markets',
    displayName: 'Piețe Emergente',
    shortLabel: 'EMERGING',
    description: 'BRICS, piețe în dezvoltare, Asia, America Latină, MSCI EM',
    keywords: [
      'piețe emergente', 'piete emergente', 'emerging markets',
      'brics', 'china', 'india', 'brazilia', 'rusia',
      'msci em', 'em etf',
      'piețe în dezvoltare', 'piete in dezvoltare',
      'asia', 'asia-pacific',
      'america latină', 'america latina', 'latam',
      'turkey', 'turcia', 'south africa',
    ],
  },
];

export const FALLBACK_THEME = 'other' as const;

import forkConfig from '../../../fork-config';

export const ACTIVE_THEMES = THEMES.filter(
  (t) => forkConfig.contentNiche.themes.includes(t.id)
);
